version: "3.7"

services:
  backend:
    container_name: backend
    image: node:14.16-buster
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
    working_dir: '/app'
    restart: "unless-stopped"
    command: bash -c "npm i && npm run build && node build/server.js"
    # command: bash -c "npm i && node -r ts-node/register src/server.ts"
    # command: bash -c "npm i && npm run dev"